import { StyleSheet } from "react-native";
const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#fff" },
  header: {
    flexDirection: "row",
    alignItems: "center",
    padding: 12,
    backgroundColor: "#2ECC71",
  },
  headerTitle: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
    marginLeft: 12,
  },
  searchBox: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#f2f2f2",
    margin: 12,
    paddingHorizontal: 10,
    borderRadius: 8,
  },
  row: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#eee",
  },
  avatarBox: { position: "relative", marginRight: 12 },
  avatar: { width: 40, height: 40, borderRadius: 20 },
  name: { fontSize: 15, fontWeight: "500" },
  time: { fontSize: 12, color: "#777" },
  allRow: {
    flexDirection: "row",
    alignItems: "center",
    padding: 12,
  },
  footer: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderTopWidth: 1,
    borderColor: "#eee",
    backgroundColor: "#fff",
  },
  selectedAvatarBox: { marginRight: 10 },
  selectedAvatar: { width: 36, height: 36, borderRadius: 18 },
  removeIcon: {
    position: "absolute",
    top: -4,
    right: -4,
    backgroundColor: "#fff",
    borderRadius: 10,
    padding: 2,
    elevation: 2,
  },
  nextBtn: {
    backgroundColor: "#2ECC71",
    width: 45,
    height: 45,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
    marginLeft: "auto",
  },
  checkOverlay: {
    position: "absolute",
    bottom: -2,
    right: -2,
    backgroundColor: "#2ECC71",
    borderRadius: 10,
    padding: 2,
  },
  amountInput: {
    width: 80,
    height: 38,
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: 8,
    textAlign: "right",
    paddingRight: 8,
    paddingVertical: 6,
    fontSize: 14,
  },
  splitEvenBtn: {
  flexDirection: "row",
  alignItems: "center",
  paddingHorizontal: 12,
  paddingVertical: 8,
  borderTopWidth: 1,
  borderColor: "#eee",
},
});

export default styles;